server:
  port: 8080
#  tomcat:
#    threads:
#      max: 5
#    max-connections: 10
#
#  boot:
#    admin:
#      client:
#        url: http://localhost:9090

#spring:
#  cache:
#    redis:
#      time-to-live: 10S
#    type: simple

